TOP=../..
include $(TOP)/configure/CONFIG

# Create and install (or just install) into <top>/db
DB += plain.db
DB += macro.db

# macros.db will be created
# from macros.substitutions!
DB += macros.db

include $(TOP)/configure/RULES

