# SPDX-FileCopyrightText: 1998 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

TOP=../..
include $(TOP)/configure/CONFIG

DB += rotation_table.db
DB += rotation_control.db

include $(TOP)/configure/RULES
