#!/bin/sh

echo "************************"
echo "** Try 'pvinfo IMAGE'  *"
echo "************************"
echo
echo

/ics/training/tools/EPICSV4Sandbox/ntndarrayServer/bin/*/ntndarrayServerMain IMAGE

